version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: conf.py

formats: all

python:
  install:
    - requirements: requirements.txt
