# GitHub Actions Workflow to cleanup the template project after it has been used to create a new repository.

name: Generate SManuscript

on:
  workflow_dispatch:
    inputs:
      template:
        description: 'Template to use'
        required: true
        default: 'ascelike-new'
        type: choice
        options:
          - 'ascelike-new'
      filename:
        description: 'File name of the manuscript'
        required: true
        default: 'manuscript'
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Copy template file
      - name: Copy template files
        run: |
          cp templates/${{ github.event.inputs.template }}.md ${{ github.event.inputs.filename }}.md

      # Commit modified files
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
