# GitHub Actions Workflow to cleanup the template project after it has been used to create a new repository.

name: Template

on:
  workflow_dispatch:
    inputs:
      template:
        description: 'Template to use'
        required: true
        default: 'ascelike-new'
        type: choice
        options:
          - 'ascelike-new'
      filename:
        description: 'Filename of paper'
        required: true
        default: 'manuscript'
        type: string

jobs:
  cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Cleanup project
      - name: Cleanup
        run: |
          git submodule deinit templates
          git rm --cached -r templates
          rm -rf LICENSE .readthedocs.yml .gitmodules .github/workflows/template-cleanup.yml docs

      # Commit modified files
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"

      # Copy template files
      - name: Copy template files
        run: cp templates/${{ github.event.inputs.template }}.md ${{ github.event.inputs.filename }}.md

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
